import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import '@fontsource-variable/dancing-script';
import '@fontsource/ubuntu';
import '@fontsource-variable/open-sans';
import '@fontsource-variable/raleway';

import Head from "next/head";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mntrscms Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      </Head>

      <body
       className="px-6 py-6"
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>

    </html>
  );
}
